### PR TITLE
Don't enable readline hook when stdin shouldn't be fixed. Code from #36.

### PR DESCRIPTION
**Pull request by thebjorn**

### CODE REVIEW

**Comment by Drekin** [comment]
Thank you for the PR. Did you try it in your setting? Also, can you please push it to the development branch?

**Comment by thebjorn** [comment]
It's working flawlessly for me and two other developers here.

I'll try to push it to the development branch when I get home..

**Comment by Drekin** [comment]
Ok, great.

**Comment by thebjorn** [comment]
Assuming I did it correctly #40 should be the same commit on the development branch.

**Pull request closed without merging**
